name: Flow Verify

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: bradennapier/eslint-plus-action@v3.4.2
      with: 
        issueSummaryType: full
        reportIgnoredFiles: true
    - name: Install dependencies
      run: npm install
    - run: npm run flow

    